### ISSUE TITLE
The game's 'basedir' isn't properly set.

### ISSUE THREAD

**Issue by iBurley** [flathub/io.github.ezQuake#4]
If you open the game and try to change your player skin it attempts to open the home directory, not the game files. I've been able to get everything working using the following command to launch the game:

`flatpak run io.github.ezQuake -basedir ~/.var/app/io.github.ezQuake/.ezquake`

**Comment by Eonfge** [comment]
Good catch. I'll push a patch out

**Comment by Eonfge** [comment]
Your comment gave me another great insight in how to improve the package configuration. I can now remove a minor path change all together. Could you test it for me, using this patch:

```
flatpak install --user https://dl.flathub.org/build-repo/18556/io.github.ezQuake.flatpakref
```

https://github.com/flathub/io.github.ezQuake/pull/5

**Comment by iBurley** [comment]
Yep, works perfectly.

**Comment by Eonfge** [comment]
Well, that seals the deal. Let's wrap it up and publish it far and wide
